// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ComodityPagination struct {
	Limit     *int        `json:"limit"`
	Page      *int        `json:"page"`
	TotalItem int         `json:"total_item"`
	Nodes     []*Comodity `json:"nodes"`
}

type LoginResponse struct {
	AccessToken string `json:"access_token"`
	User        *User  `json:"user"`
}

type LoginUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewUser struct {
	Username        string  `json:"username"`
	Email           string  `json:"email"`
	Role            string  `json:"role"`
	WhatsappNumber  *string `json:"whatsapp_number"`
	Password        string  `json:"password"`
	ConfirmPassword string  `json:"confirm_password"`
}

type User struct {
	Username       string `json:"username"`
	Email          string `json:"email"`
	Role           string `json:"role"`
	WhatsappNumber string `json:"whatsapp_number"`
	HashedPassword string `json:"hashed_password"`
}

type UserOps struct {
	Register *string        `json:"register"`
	Login    *LoginResponse `json:"login"`
}
